apiVersion: v1
kind: Service
metadata:
  name: testmcp
  labels:
    run: testmcp
spec:
  type: NodePort
  selector:
    app: testmcp
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30316
